default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: nazarhlynskyi
  password: 

development:
  <<: *default
  database: dev_pivorak

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: myapp_production
  username: myapp
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>